SELECT distinct
	c.TABLE_NAME,
	c.ORDINAL_POSITION,
	c.COLUMN_NAME,
	c.DATA_TYPE,
	c.CHARACTER_MAXIMUM_LENGTH,
	c.NUMERIC_PRECISION,
	c.COLUMN_DEFAULT,
	CASE WHEN c.IS_NULLABLE = 'NO' THEN 'False' ELSE 'True' END 'IS_NULLABLE',
	CASE WHEN 
		(SELECT count(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE cu 
			JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS co ON cu.CONSTRAINT_NAME = co.CONSTRAINT_NAME 
			WHERE co.CONSTRAINT_TYPE = 'PRIMARY KEY' AND c.TABLE_NAME = cu.TABLE_NAME AND c.COLUMN_NAME = cu.COLUMN_NAME
		) = 0 THEN 'False' ELSE 'True' END 'PRIMARY KEY',
	CASE WHEN 
		(SELECT count(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE cu 
			JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS co ON cu.CONSTRAINT_NAME = co.CONSTRAINT_NAME 
			WHERE co.CONSTRAINT_TYPE = 'UNIQUE' AND c.TABLE_NAME = cu.TABLE_NAME AND c.COLUMN_NAME = cu.COLUMN_NAME
		) = 0 THEN 'False' ELSE 'True' END 'UNIQUE KEY',
	CASE WHEN 
		(SELECT COUNT(*) FROM sys.indexes i 
			JOIN sys.objects o ON i.object_id = o.object_id
			JOIN sys.index_columns ic ON ic.object_id = i.object_id AND ic.index_id = i.index_id
			JOIN sys.columns co ON co.object_id = i.object_id AND co.column_id = ic.column_id
			WHERE i.[type] = 2 AND i.is_unique = 0 AND i.is_primary_key = 0 AND o.[type] = 'U' AND co.name = c.COLUMN_NAME AND o.name = c.TABLE_NAME
		) = 0 THEN 'False' ELSE 'True' END 'INDEX KEY',
	CASE WHEN 
	(SELECT count(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE cu 
		JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS co ON cu.CONSTRAINT_NAME = co.CONSTRAINT_NAME 
		WHERE co.CONSTRAINT_TYPE = 'FOREIGN KEY' AND c.TABLE_NAME = cu.TABLE_NAME AND c.COLUMN_NAME = cu.COLUMN_NAME
		) = 0 THEN 'False' ELSE 'True' END 'FOREIGN KEY',	
	(SELECT TOP 1 cu2.TABLE_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE cu
		JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS co ON cu.CONSTRAINT_NAME = co.CONSTRAINT_NAME
		JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE cu2 ON cu2.CONSTRAINT_NAME = co.UNIQUE_CONSTRAINT_NAME
		WHERE c.TABLE_NAME = cu.TABLE_NAME AND c.COLUMN_NAME = cu.COLUMN_NAME) 'FKTABLE',
	(SELECT TOP 1 cu2.COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE cu
		JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS co ON cu.CONSTRAINT_NAME = co.CONSTRAINT_NAME
		JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE cu2 ON cu2.CONSTRAINT_NAME = co.UNIQUE_CONSTRAINT_NAME
		WHERE c.TABLE_NAME = cu.TABLE_NAME AND c.COLUMN_NAME = cu.COLUMN_NAME) 'FKCOLUMN',
	CASE WHEN 
		(SELECT count(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE cu
			JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS co ON cu.CONSTRAINT_NAME = co.CONSTRAINT_NAME
			JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE cu2 ON cu2.CONSTRAINT_NAME = co.UNIQUE_CONSTRAINT_NAME
			WHERE c.COLUMN_NAME = cu2.COLUMN_NAME
		) = 0 THEN 'False' ELSE 'True' END 'FKREFERENCED'

FROM INFORMATION_SCHEMA.COLUMNS c
	LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE cu
		ON  cu.TABLE_NAME = c.TABLE_NAME AND
			cu.COLUMN_NAME = c.COLUMN_NAME
	LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS co
		ON co.CONSTRAINT_NAME = cu.CONSTRAINT_NAME

WHERE c.TABLE_NAME != 'sysdiagrams'

ORDER BY TABLE_NAME, c.ORDINAL_POSITION